Repository HongRae-Kim/SW_5, pull requests merged in 2024-12, with the labels that each got.

#26 Feature/accommodation prompt
  chatBotApp.py
Labels: backend, feat

#25 태근님 소개페이지 구현
  20241203.png
  Home.py
  __pycache__/Home.cpython-311.pyc
  __pycache__/chatBotApp.cpython-311.pyc
Labels: frontend, UI

#15 OpenWeather API(API key 수정 버전)
  README.md
  chatBotApp.py
Labels: backend, feat

#30 Ajust column size by window size
  Home.py
  __pycache__/Home.cpython-312.pyc
  __pycache__/chatBotApp.cpython-312.pyc
  chatBotApp.py
Labels: frontend
